# Generated by Django 3.0.4 on 2020-03-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200308_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapbooktable',
            name='picture',
            field=models.FileField(upload_to='App/media/images/'),
        ),
    ]
