# Generated by Django 3.0.4 on 2020-03-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200308_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapbooktable',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
